name: Build and Upload Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: EFBenchmarker.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      ACTIONS_STEP_DEBUG: true 

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4.1.0
      with:
        # Optional SDK version(s) to use. If not provided, will install global.json version when available. Examples: 2.2.104, 3.1, 3.1.x, 3.x, 6.0.2xx
        dotnet-version: '8.0'
          

    # Restore Nuget packages
    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    - name: Restore NuGet packages
      run: nuget restore $env:Solution_Name

    # Build
    - name: Build the EFBenchmark
      run: msbuild EFBenchmark\EFBenchmark.csproj /p:Configuration=Release

    # Build
    - name: Build the SQLBenchmark
      run: dotnet build SQLBenchmark\SQLBenchmark.csproj --configuration Release --no-restore
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: EFBenchmark
        path: EFBenchmark\bin\Release\

    - name: Upload Build Artifact SQL Benchmark
      uses: actions/upload-artifact@v4
      with:
        name: SQLBenchmark
        path: SQLBenchmark\bin\Release\

