name: Build and Upload Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: EFBenchmarker.sln                       # Replace with your solution name, i.e. MyWpfApp.sln.
      Project_Directory: EFBenchmark    # Replace with the project directory relative to the solution, i.e. MyWpfApp.Package.

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Restore Nuget packages
    - name: Restore NuGet packages
      run: nuget restore YourSolution.sln

    # Build
    - name: Build the solution
      run: msbuild $env:Solution_Name /p:Configuration=Release

    - name: Zip the Release Folder
      run: |
        powershell Compress-Archive -Path $env:Project_Directory\bin\Release\* -DestinationPath $env:Project_Directory.zip

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: $env:Project_Directory
        path: $env:Project_Directory.zip

